lidar:
  pointcloud_topic: /mid/points
  processed_cloud_topic: /perception/processed_cloud
  
  floor_height_threshold: 0.1
  max_height: 10.0
  
  cluster_tolerance: 0.3
  min_cluster_size: 10
  max_cluster_size: 50000

  box:
    min_width: 0.5
    max_width: 1.2
    min_height: 0.5
    max_height: 1.2
    min_depth: 0.5
    max_depth: 1.2
  
  bridge:
    min_width: 1.0
    max_width: 2.0
    min_length: 3.5
    max_length: 6.0
    
  debug_mode: true
  enable_cluster_visualization: true
