yolo_detector:
  min_confidence: 0.75

fusion_node:
  num_closest_points: 3   
  merge_distance: 0.8

furthest_box_navigator:
  overlap_threshold: 0.6
  bridge_length: 3.0
  yaw_bin_size: 20

pseudo_status:
  min_dist: 4.5

fusion_merged_node:
  box_big_size: 1.2
  point_inside_ratio_threshold: 0.8
  max_history: 30
  # unmatch_max: 10

fallback_navigator:
  inflate_ratio: 1.2             # Initial inflation ratio
  max_inflate_ratio: 2.5         # Maximum inflation ratio
  inflate_step: 0.2              # Increment per iteration
  box_size: 0.8                  # Original box size
  x_range: [2.0, 22.0]           # Exploration area X range
  y_range: [11.0, 19.0]          # Exploration area Y range
  wait_time: 0.5                 # Wait time after arrival (seconds)





  
