#Configuation for robot odometry EKF
#
frequency: 50

odom0: /jackal_velocity_controller/odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, true,
               false, false, true,
               false, false, false]
odom0_differential: false

imu0: /imu/data/bias_filtered
imu0_config: [false, false, false,
              true, true, false,
              false, false, false,
              true, true, true,
              false, false, false]
imu0_differential: false

odom_frame: odom
base_link_frame: base_link
world_frame: odom

predict_to_current_time: true
publish_tf: true

# use_control: false

# --- Pose source from NDT ---
# pose0: /ndt/pose
# pose0_config: [true, true, false,
#                false, false, true,
#                false, false, false,
#                false, false, true]
# pose0_differential: false
# pose0_relative: false

# pose0: /ndt/pose_converted
# pose0_config: [true, true, false,
#                false, false, false,
#                false, false, false,
#                true, true, true,
#                false, false, false]
# pose0_differential: false

# ekf_localization_node:
#   odom0: /ndt/pose_converted
#   odom0_config: [true, true, true, false, false, false, false, false, false, false, false, false, false, false, false]
#   pose0_differential: false


# odometry0: /ndt/pose
# odometry0_config: [true, true, true, true, true, true,
#                    false, false, false, false, false, false,
#                    false, false, false, false, false, false]
# odometry0_differential: false
# odometry0_relative: false