local_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 20.0
   publish_frequency: 5.0
   width: 10.0
   height: 10.0
   resolution: 0.05
   static_map: false
   rolling_window: true

   # added
   inflater_layer:
      cost_scaling_factor: 2 #4 #3 #1 #2
      # inflation_radius: 1.5
      inflation_radius: 0.3 #0.25 #0.27 #0.3